apiVersion: v1
kind: Service
metadata:
  name: kubeflow-loadbalancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "kubeflow-loadbalancer"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
